[2025-08-20 18:31:03] - logger:_log - INFO - Logger initialized. Logs will be saved to c:\Users\ss255385\OneDrive - Teradata Corporation\Desktop\AMuRD-Iteration-7\src\logs\borai_20250820_183103.log
[2025-08-20 18:46:39] - logger:_log - INFO - TeradataDatabase instance initialized
[2025-08-20 18:46:39] - logger:_log - INFO - Operation 'Database connection' started - Details: {'host': 'iteration7-gwyyqrtdecxxq4xk.env.clearscape.teradata.com', 'database': 'demo_user'}
[2025-08-20 18:46:52] - logger:_log - INFO - Operation 'Database connection' completed
[2025-08-20 18:46:52] - logger:_log - INFO - Operation 'Query execution' started - Details: {'query': '\nSELECT * FROM TD_ClassificationEvaluator (\n   ON demo_user.results AS InputTable\n   OUT PERMANENT T...'}
[2025-08-20 18:46:52] - logger:_log - ERROR - query execution : Exception: [Version 20.0.0.34] [Session 1559] [Teradata Database] [Error 3803] Table 'classification_metrics' already exists.
 at gosqldriver/teradatasql.formatError ErrorUtil.go:83
 at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError ErrorUtil.go:190
 at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError ErrorUtil.go:206
 at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:340
 at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:2597
 at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:1073
 at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:792
 at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122
 at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:823
 at database/sql.ctxDriverQuery ctxutil.go:48
 at database/sql.(*DB).queryDC.func1 sql.go:1786
 at database/sql.withLock sql.go:3574
 at database/sql.(*DB).queryDC sql.go:1781
 at database/sql.(*Conn).QueryContext sql.go:2037
 at main.createRows goside.go:1080
 at main.goCreateRows goside.go:959
 at _cgoexp_ff5e33a08e40_goCreateRows _cgo_gotypes.go:417
 at runtime.cgocallbackg1 cgocall.go:446
 at runtime.cgocallbackg cgocall.go:350
 at runtime.cgocallback asm_amd64.s:1084
 at runtime.goexit asm_amd64.s:1700
[2025-08-20 18:47:10] - logger:_log - INFO - Operation 'Query execution' started - Details: {'query': '\nSELECT * FROM TD_ClassificationEvaluator (\n   ON demo_user.results AS InputTable\n   OUT PERMANENT T...'}
[2025-08-20 18:47:10] - logger:_log - INFO - Operation 'Query execution' completed - Details: {'rows_returned': 0}
[2025-08-20 18:55:21] - logger:write - ERROR - Exception ignored in: <bound method IPythonKernel._clean_thread_parent_frames of <ipykernel.ipkernel.IPythonKernel object at 0x0000017E271681A0>>Traceback (most recent call last):
[2025-08-20 18:55:21] - logger:write - ERROR -   File "C:\Users\ss255385\AppData\Roaming\Python\Python313\site-packages\ipykernel\ipkernel.py", line 796, in _clean_thread_parent_frames
[2025-08-20 18:55:21] - logger:write - ERROR - active_threads = {thread.ident for thread in threading.enumerate()}  File "c:\Users\ss255385\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1479, in enumerate
[2025-08-20 18:55:21] - logger:flush - ERROR - def enumerate():KeyboardInterrupt:
